# Generated by Django 2.2.2 on 2019-06-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklychallenges',
            name='week',
            field=models.IntegerField(default=0),
        ),
    ]
