# Generated by Django 2.2.2 on 2019-06-19 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_weeklychallenges_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklychallenges',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Easy', max_length=10),
        ),
    ]
