# Generated by Django 2.2.2 on 2019-06-20 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190619_1047'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeeklyChallenges',
        ),
    ]
