# Generated by Django 2.2.2 on 2019-06-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_auto_20190620_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklychallenges',
            name='constraints',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='weeklychallenges',
            name='input_format',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='weeklychallenges',
            name='output_format',
            field=models.TextField(),
        ),
    ]
