# Generated by Django 2.2.2 on 2019-06-21 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_auto_20190621_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField(default=0)),
                ('problem_name', models.CharField(max_length=50, unique=True)),
                ('problem', models.TextField()),
                ('input_format', models.TextField()),
                ('output_format', models.TextField()),
                ('constraints', models.TextField()),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Easy', max_length=10)),
                ('input_example', models.TextField()),
                ('output_example', models.TextField()),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='contestName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest', models.CharField(choices=[('Weekly Challenges Series', 'Weekly Challenges Series'), ('Other Contests', 'Other Contests')], max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='WeeklyChallenges',
        ),
        migrations.AddField(
            model_name='challenges',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.contestName'),
        ),
    ]
